/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appSisPlan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sisPlanDAL.RestauranteDAL;
import sisPlanEntidades.Restaurante;

/**
 *
 * @author moise
 */
public class JFrmMejoresTres extends javax.swing.JFrame {

    ArrayList<Restaurante> listaRestaurante;

    /**
     * Creates new form JfrmMejoresTres
     */
    public JFrmMejoresTres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTerceraPosicion = new javax.swing.JLabel();
        lblSegundaPosicion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPrimeraPosicion = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Top 3");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOP 3 MEJORES RESTAURANTES PUNTUADOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblTerceraPosicion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTerceraPosicion.setForeground(new java.awt.Color(255, 102, 51));
        lblTerceraPosicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTerceraPosicion.setText(" ");
        jPanel1.add(lblTerceraPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, 30));

        lblSegundaPosicion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSegundaPosicion.setForeground(new java.awt.Color(102, 102, 102));
        lblSegundaPosicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblSegundaPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/podio.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 420, 160));

        lblPrimeraPosicion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPrimeraPosicion.setForeground(new java.awt.Color(102, 102, 0));
        lblPrimeraPosicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrimeraPosicion.setText(" ");
        jPanel1.add(lblPrimeraPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 137, 120, 30));

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            listaRestaurante = RestauranteDAL.todosRestaurantes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        lblPrimeraPosicion.setText(imprimirPosicion());
        lblSegundaPosicion.setText(imprimirPosicion());
        lblTerceraPosicion.setText(imprimirPosicion());
    }//GEN-LAST:event_formWindowOpened

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    //IMPRIMIR LOS 3 MEJORES RESTAURANTES CON MAYOR PUNTUACION
    public String imprimirPosicion() {
        String posicion = "";
        Restaurante mayor = listaRestaurante.get(0);
        for (Restaurante restaurante : listaRestaurante) {
            if (restaurante.retornaPromedioPuntuado() > mayor.retornaPromedioPuntuado()) {
                mayor = restaurante;
            }

        }
        posicion = mayor.getNombre() + " - " + mayor.retornaPromedioPuntuado() + " ✪ ";
        ArrayList<Restaurante> listaModificada = new ArrayList<>();
        for (Restaurante restaurante : listaRestaurante) {
            if (!restaurante.getCodigo().equals(mayor.getCodigo())) {
                listaModificada.add(restaurante);
            }
        }
        listaRestaurante = listaModificada;
        return posicion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMejoresTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMejoresTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMejoresTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMejoresTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMejoresTres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPrimeraPosicion;
    private javax.swing.JLabel lblSegundaPosicion;
    private javax.swing.JLabel lblTerceraPosicion;
    // End of variables declaration//GEN-END:variables
}
