/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appSisPlan;

import sisPlanEntidades.Usuario;

/**
 *
 * @author moise
 */
public class JFrmMenuCliente extends javax.swing.JFrame {

    Usuario usuarioActivo;

    /**
     * Creates new form jFrmMenuCliente
     */
    public JFrmMenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnCalificar = new javax.swing.JButton();
        jbtnCompra = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Cliente");

        jPanel1.setToolTipText("Elección del Cliente");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCalificar.setBackground(new java.awt.Color(0, 0, 0));
        jbtnCalificar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnCalificar.setText("Calificar pedidos");
        jbtnCalificar.setOpaque(false);
        jbtnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalificarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCalificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, 30));

        jbtnCompra.setBackground(new java.awt.Color(0, 0, 0));
        jbtnCompra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnCompra.setText("Ordenar");
        jbtnCompra.setOpaque(false);
        jbtnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCompraActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 30));

        jBtnSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Logo de Uber Eats.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCompraActionPerformed
        JFrmCompra compra = new JFrmCompra();
        sisPlanUtilitarios.UtilitarioVentana.centrarVentanaJFrame(compra, false);
//        compra.setLocationRelativeTo(null);
        compra.setUsuarioActivo(usuarioActivo);
//        compra.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jbtnCompraActionPerformed

    private void jbtnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalificarActionPerformed
        JFrmCalificacion calificacion = new JFrmCalificacion();
        sisPlanUtilitarios.UtilitarioVentana.centrarVentanaJFrame(calificacion, false);
//        calificacion.setLocationRelativeTo(null);
        calificacion.setUsuarioActivo(usuarioActivo);
//        calificacion.setVisible(true);
    }//GEN-LAST:event_jbtnCalificarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenuCliente().setVisible(true);
            }
        });
    }

    public Usuario getUsuarioActivo() {
        return usuarioActivo;
    }

    public void setUsuarioActivo(Usuario usuarioActivo) {
        this.usuarioActivo = usuarioActivo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCalificar;
    private javax.swing.JButton jbtnCompra;
    // End of variables declaration//GEN-END:variables

}
