/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appSisPlan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sisPlanDAL.OrdenCompraDAL;
import sisPlanDAL.RestauranteDAL;
import sisPlanEntidades.LineaDetalle;
import sisPlanEntidades.OrdenCompra;
import sisPlanEntidades.Producto;
import sisPlanEntidades.Usuario;

/**
 *
 * @author moise
 */
public class JFrmCalificacion extends javax.swing.JFrame {

    Usuario usuarioActivo;

    /**
     * Creates new form jFrmCalificacion
     */
    public JFrmCalificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jcboCalificacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcboProductos = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcboOrdenes = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calificación");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Logo de Uber Eats.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 410, 380));

        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/AnteriorPagina.png"))); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/Aceptar.png"))); // NOI18N
        jButton1.setText("Calificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, 40));

        getContentPane().add(jcboCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisPlanImagenes/star_32px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 40, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Calificación");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        getContentPane().add(jcboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 230, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Productos");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 20));

        jcboOrdenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboOrdenesItemStateChanged(evt);
            }
        });
        getContentPane().add(jcboOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Número de orden");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcboOrdenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboOrdenesItemStateChanged
        LLenarProductoEImprimirDetalle();
    }//GEN-LAST:event_jcboOrdenesItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //VALIDAR QUE TODO NO ESTE EN BLANCO
        if (jcboCalificacion.getSelectedIndex() == -1 || jcboOrdenes.getSelectedIndex() == -1 || jcboProductos.getSelectedIndex() == 1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciones orden de compra, producto y calificación.");
            return;
        }
        
        //METODO PARA CALIFICAR EL RESTAURANTE
        try {
            RestauranteDAL.insertaCalificacionRestaurante(((OrdenCompra) jcboOrdenes.getSelectedItem()).getRestaurante(),
                     (int) jcboCalificacion.getSelectedItem());
            jcboProductos.removeItemAt(jcboProductos.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Gracias por tu calificación.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        llenarFacturas();
        llenarPuntuacion();
    }//GEN-LAST:event_formWindowOpened

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    //IMPRIMIR LOS DETALLES QUE REALIZO EL CLIENTE SEMEJANTE A LA FACTURA ELECTRONICA
    public void LLenarProductoEImprimirDetalle() {
        StringBuilder detalle = new StringBuilder();
        OrdenCompra ordenDetalle = (OrdenCompra) jcboOrdenes.getSelectedItem();
        detalle.append("Restaurante: ").append(ordenDetalle.getRestaurante().getNombre()).append("\n");
        jcboProductos.removeAllItems();
        for (LineaDetalle linea : ordenDetalle.getArraLineaDetalle()) {
            detalle.append(linea.toString()).append("\n\n\n");
            jcboProductos.addItem(linea.getoProducto());
        }
        jcboProductos.setSelectedIndex(-1);
        jTextArea1.setText(detalle.toString());
    }

    //LLENAR LAS FACTURAS EN UN TXTAREA PARA QUE VEA EL CLIENTE LAS COMPRAS QUE A REALIZADO
    public void llenarFacturas() {
        try {
            ArrayList<OrdenCompra> ordenes = OrdenCompraDAL.listaFacturas(usuarioActivo.getCodigo());
            for (OrdenCompra orden : ordenes) {
                orden.setCliente(usuarioActivo);
                jcboOrdenes.addItem(orden);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }
    
    //LENAR LA PUNTACION DE LOS CLIENTES QUE LO A CALIFICADO CON UN FOR EACH
    public void llenarPuntuacion() {
        for (int i = 1; i <= 5; i++) {
            jcboCalificacion.addItem(i);
        }
        jcboCalificacion.setSelectedIndex(-1);
    }

    public Usuario getUsuarioActivo() {
        return usuarioActivo;
    }

    public void setUsuarioActivo(Usuario usuarioActivo) {
        this.usuarioActivo = usuarioActivo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmCalificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<Integer> jcboCalificacion;
    private javax.swing.JComboBox<OrdenCompra> jcboOrdenes;
    private javax.swing.JComboBox<Producto> jcboProductos;
    // End of variables declaration//GEN-END:variables
}
